name: Generate Code from OpenAPI

on:
  schedule:
    // Every Monday at 1PM UTC (9AM EST)
    0 13 * * 1
    
jobs:
  generate_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate code
        uses: hatamiarash7/openapi-generator@v0.2.0
        with:
          generator: python
          openapi-url: https://stoplight.io/api/v1/projects/spacetraders/spacetraders/nodes/reference/SpaceTraders.json?fromExportButton=true&snapshotType=http_service&deref=optimizedBundle
